services:
  db:
    image: "postgres:15"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DATABASE}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  backend:
    image: ${IMAGE}:${TAG}
    build:
      context: .
    command: [ "migrate", "run" ]
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE
      - DB_USER
      - DB_PASSWORD
      - DB_TZ=Europe/Moscow
    restart: always
    depends_on: 
      db:
        condition: service_healthy
        restart: true
    ports:
      - 8080:8080
volumes:
  pgdata:
